services:
  - type: web
    name: medusa-shop-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx medusa db:migrate && npm run start
    plan: free
    region: frankfurt
